// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDcfUc4g4D-bkRe-cHzVaWnKYXCuvg3NnM",
      authDomain: "o1ne-1da57.firebaseapp.com",
      projectId: "o1ne-1da57",
      storageBucket: "o1ne-1da57.appspot.com",
      messagingSenderId: "519845730643",
      appId: "1:519845730643:web:21389487b0e851bbade9a6",
      measurementId: "G-MS359LDP57");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdt2OmuWCv2XXTeX6yqNNf8LYF8yHWGV8',
    appId: '1:519845730643:android:089f9a94267df558ade9a6',
    messagingSenderId: '519845730643',
    projectId: 'o1ne-1da57',
    storageBucket: 'o1ne-1da57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPpmA1w-MZWdOI8UGaZrLIsHbx5Fl_qqY',
    appId: '1:519845730643:ios:65cac7b9b799d32bade9a6',
    messagingSenderId: '519845730643',
    projectId: 'o1ne-1da57',
    storageBucket: 'o1ne-1da57.appspot.com',
    iosBundleId: 'com.oneuser.oneuser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPpmA1w-MZWdOI8UGaZrLIsHbx5Fl_qqY',
    appId: '1:519845730643:ios:65cac7b9b799d32bade9a6',
    messagingSenderId: '519845730643',
    projectId: 'o1ne-1da57',
    storageBucket: 'o1ne-1da57.appspot.com',
    iosBundleId: 'com.oneuser.oneuser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcfUc4g4D-bkRe-cHzVaWnKYXCuvg3NnM',
    appId: '1:519845730643:web:492e0dc9ebf705a0ade9a6',
    messagingSenderId: '519845730643',
    projectId: 'o1ne-1da57',
    authDomain: 'o1ne-1da57.firebaseapp.com',
    storageBucket: 'o1ne-1da57.appspot.com',
    measurementId: 'G-N4DR79Z56N',
  );
}
